using System.Text;
using System.Text.Json;
using SddOrchestrator.Models;

namespace SddOrchestrator.Services;

public sealed class ReportRenderer
{
    public string Render(IReadOnlyList<AgentInvocationResult> results)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# 🌅 Morning SDD Triangulation — {DateTime.Now:yyyy-MM-dd HH:mm}");
        sb.AppendLine();
        sb.AppendLine("> Generated by SddOrchestrator. Three specialized agents, each with a narrow concern, a targeted prompt, and the right-sized model.");
        sb.AppendLine();

        sb.AppendLine("## Run summary");
        sb.AppendLine();
        sb.AppendLine("| Agent | Status | Duration |");
        sb.AppendLine("|-------|--------|----------|");
        foreach (var r in results)
            sb.AppendLine($"| `{r.AgentName}` | {(r.Success ? "✅ ok" : "❌ failed")} | {r.Duration.TotalSeconds:F1}s |");
        sb.AppendLine();

        foreach (var result in results)
        {
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine($"## Agent: `{result.AgentName}`");
            sb.AppendLine();

            if (!result.Success)
            {
                sb.AppendLine($"❌ **Failed**: {result.Error}");
                sb.AppendLine();
                if (!string.IsNullOrWhiteSpace(result.RawOutput))
                {
                    sb.AppendLine("<details><summary>Raw output</summary>");
                    sb.AppendLine();
                    sb.AppendLine("```");
                    sb.AppendLine(result.RawOutput);
                    sb.AppendLine("```");
                    sb.AppendLine();
                    sb.AppendLine("</details>");
                }
                continue;
            }

            sb.AppendLine(RenderJsonBody(result.JsonPayload!));
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string RenderJsonBody(string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var pretty = JsonSerializer.Serialize(doc.RootElement, new JsonSerializerOptions { WriteIndented = true });
            return $"```json\n{pretty}\n```";
        }
        catch
        {
            return $"```\n{json}\n```";
        }
    }
}
